### ISSUE TITLE
Import animations unrelated properties

### ISSUE THREAD

**Issue by feelingsonice** [viniciusgerevini/godot-aseprite-wizard#118]
I attached a screenshot of what I mean. In the screenshot, `texture`, `hframes`, `vframes`, `visible` are all properties that were all set in the beginning of the frame and totally unrelated to the animation? Perhaps this is a feature? Could someone clarify? My settings are also attached in the second screenshot.

![Screenshot 2024-01-21 at 8 19 29 PM](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/42384776/52e8644b-b392-4ed8-9c37-6d0a94709acc)

![Screenshot 2024-01-21 at 8 21 21 PM](https://github.com/viniciusgerevini/godot-aseprite-wizard/assets/42384776/470ba06c-c437-4ae8-bef1-3bd2e7e777fd)

**Comment by viniciusgerevini** [comment]
Hello @feelingsonice . These were added as part of a feature to support multiple sprites in a single animation player. Given we can only set one file to each Sprite/TextureRect I guess `hframes` , ` vframes` and `texture` are redundant, but I'll have to look into it to confirm it was not added due to some edge case. Here is the PR introducing the feature in case you are interested #64.

The `visible` track is for the "Hide unused sprites" option. One use-case example is if you have a layered character and there is a "weapon" layer that is imported from a different sprite and only has the "attack" animation. When this layer is not used in an animation it should be hidden, otherwise it will be shown in its default position.

Thanks for reporting this. I'll check if those properties I mentioned can be removed and if it can be done without breaking changes. Cheers.

**Comment by viniciusgerevini** [comment]
Included in the latest release (7.2.0 Godot 4, 6.3.0 Godot 3). Already available in the branch and release page. It takes a few days for it to be available in Godot's asset lib. Cheers.
