### ISSUE TITLE
Automatically import all sprites in my project in one go

### ISSUE THREAD

**Issue by sandord** [viniciusgerevini/godot-aseprite-wizard#134]
Now and then I make changes to quite a few aseprite files. Then, to re-import them in my Godot project I have to work through all related scenes and select the sprite nodes and then the Import button. This is quite a tedious task.

It would be really really cool if there was a way to automatically import all sprites in my project in one go.

**Comment by sandord** [comment]
That being said, your addon is by far the best there is out there, compared to competing add-ons 👍

**Comment by Skyflieger** [comment]
Would love that feature. Or a way to import every file in one folder recursively into another. Would make handling with a large number of files way better.

**Comment by viniciusgerevini** [comment]
@sandord Thanks. This sounds like a good feature to have. I'll look into it. Before there were some limitations that would require some external files to solve this so I never invested on it, but now it should be possible.

**Comment by viniciusgerevini** [comment]
> Or a way to import every file in one folder recursively into another.

@Skyflieger not sure I follow this one. Can you give me an example on how would you use this?

**Comment by Skyflieger** [comment]
> > Or a way to import every file in one folder recursively into another.
> > @Skyflieger not sure I follow this one. Can you give me an example on how would you use this?

@viniciusgerevini maybe in the wizard if we select a folder rather than a file, the tool goes over all files in that folder and processes them according to the seconds

Example:

-AsepriteFolder
------Folder1
--------------File1.aseprite
------File2.aseprite
-SpritesFolder

I select the AsepriteFolder and want the processed resouces to be out in the SpritesFolder so we end up like this:

-AsepriteFolder
------Folder1
--------------File1.aseprite
------File2.aseprite
-SpritesFolder
------Folder1
--------------File1.png
--------------File1.res
------File2.png
------File2.res

**Comment by viniciusgerevini** [comment]
Oh! I see. That makes sense. For some reason I didn't think about the wizard screen when you mentioned this. Thanks

**Comment by viniciusgerevini** [comment]
Changes from linked PRs are already in the asset lib (v7.4.0). It looks quite stable from my testing, but async operations can be tricky, so please report any bug as a new issue. Cheers.

**Comment by sandord** [comment]
I intended to say this last week but didn't get around to doing it: this is great news! I've been too busy to try it out yet but I certainly will!

**Comment by viniciusgerevini** [comment]
Thank you :)

**Comment by sandord** [comment]
I'm very happy with the way it works now. This saves me a lot of time! Thank you again!
