### ISSUE TITLE
Loop settings are removed from project file since 7.4.0

### ISSUE THREAD

**Issue by sandord** [viniciusgerevini/godot-aseprite-wizard#147]
I noticed that everytime I edit the project, the following is removed from the project file. It looks like a bug because those aren't the defaults and I want to keep these values active.

```
[aseprite]

animation/loop/enabled=false
animation/loop/exception_prefix="loop_"
```

**Comment by viniciusgerevini** [comment]
Ooh, I see the issue. Recently I added a cleanup for when Godot is closed, because it was crashing in MacOS. What I didn´t noticed is that the cleanup actually removes all the properties. That should be a quick fix. I'll send it today. Thank you

In the meantime if you want to stop this from happening, you can go to `addons/AsepriteWizard/plugin.gd` and comment line 60. `config.clear_project_settings()`

**Comment by sandord** [comment]
Perfect, thanks a lot for fixing this.
