### ISSUE TITLE
Feature Suggestion: Options to enable compatibility to Libresprite

### ISSUE THREAD

**Issue by RanolP** [viniciusgerevini/godot-aseprite-wizard#159]
## Problem Situation

I'm building a CI for my game and found that Aseprite disallows the re-distribution of its executable file, so I need to pick one of the following options.

1. Build on my local machine as a runner
2. Build Aseprite entirely on the CI machine

But I don't want to do all of them, so I found an alternative for Aseprite called [LibreSprite](https://libresprite.github.io/). It is the open-source fork of the Aseprite branched before the Aseprite owners made changes to their license.

## Feature Request

Since it is a fork, it has most features of the Aseprite but lacks some of them; like `--list-slices` flag.
But in my short investigation, it complies with most of Aseprite's features used by this addon.
So I'd like to suggest how about LibreSprite compatibility mode support.
When it has been enabled, The addon has a restricted feature set (as LibreSprite has no support) but can work with LibreSprite out-of-the-box, as Aseprite does.

**Comment by viniciusgerevini** [comment]
Hello @RanolP . Thanks for the suggestion. There are a few things to cover here.

First of all, as long as you are not re-distributing your CI images or creating a system for others to use, setting up Aseprite in your CI is not against Aseprite's policy. If you check their documentation, their license allows installing Aseprite in multiple machines. A CI would be just another machine, as long as it's for your own use. 

Now, about LibreSprite support. Adding official support to LibreSprite would add extra load to this plugin, making it more complex and possibly hindering what can be achieved with it. Unfortunately, I don't have the time or energy for that.

Even though it's an honourable thing to keep LibreSprite alive, there is not much going on there. Their only release is from 2021 and I don't think their goals is to keep up with Aseprite or even develop their own features. There were many features and bugfixes implemented in Aseprite since then. Many of them are CLI improvements and change in behaviour that are not necessarily visible as an end user feature, but allow this plugin to work the way it does.

For people wanting to use LibreSprite, you can either use the last version that works with it (the slice feature you mentioned was added on version v7.4.0, so the version before that should still be compatible (https://github.com/viniciusgerevini/godot-aseprite-wizard/releases/tag/v7.2.0-4), or fork this and make the changes required.

I hope this makes sense. Thanks for the discussion.

**Comment by RanolP** [comment]
Thank you for your response. I greatly appreciate your efforts and dedication to maintaining this addon.

I understand the situation now. But since I've decided to open-source my game once development is complete, the CI pipeline could be classified as a redistribution. Therefore, I will need to use LibreSprite or a similar tool.

However, I realize that supporting LibreSprite while ensuring an ergonomic and feature-rich Aseprite import experience is challenging.

Based on your suggestion, I will stick to the version compatible with LibreSprite and consider forking the repository if needed.

Thank you for your kindness. Have a great day!

P.S.: I will close this issue as "not planned" just for the record.

**Comment by viniciusgerevini** [comment]
@RanolP thank you. There is also another option I forgot to mention. If instead of using the automatic importers you use the Inspector dock or Wizard flow, you don't need to have aseprite in the CI.

Aseprite would only be required on the developer's machine when editing or creating new files. The downside is that you don't get the instant file update when editing the Aseprite files, but that allows you to keep Aseprite as a local tool, as whatever spriteframes / spritesheet that were generated before will be shipped as final and won't need to be regenerated when starting on a new machine.

Good luck with your project. It sounds interesting. Cheers.
