### ISSUE TITLE
spritesheets with alternate layouts

### ISSUE THREAD

**Issue by furroy** [viniciusgerevini/godot-aseprite-wizard#16]
so far the importer seems to work great IF you laid it out with animations the way this tool is expecting them.  i have some assets where someone made the layers be the anims, and i can't figure out how to import them and maintain my sanity.  if i use the "split  layers" they do come in, but then i have dozens of res files that need to be combined.  any ideas?  [example](https://i.gyazo.com/8a8667393f2253fdf876aa6a9356e7fe.png)

**Comment by viniciusgerevini** [comment]
Hello @furroy. Unfortunatelly the plugin does not support this organization and I don't have plans to support it, because it brings many limitations to what features you can use.

It forces each animation to have the same number of frames, same frame duration, you are not able to use animation direction (like reverse, ping-pong) and I don't think you'd able to group all layers as a same spritesheet png.

You may have your reasons to organise your animations like this, but I'd suggest changing it to use proper tags and layers. In the long run, it will make your life easier and allow you to use Aseprite's full potential.

Is there any specific reason why you prefer to use it like this?

**Comment by furroy** [comment]
i don't prefer it, i bought some assets someone else made and this is how they came. i'll probably just move all the frames around in aseprite, just thought i'd ask in case there was some less manually intensive way of dealing with it.

**Comment by viniciusgerevini** [comment]
I see. Yeah, it makes sense. Good luck.
