### ISSUE TITLE
Did not find aseprite executable

### ISSUE THREAD

**Issue by benthillerkus** [viniciusgerevini/godot-aseprite-wizard#26]
Hi, we tried the version from the Godot Asset store and on the two Windows 10 machines we've tested, we go the error message that says, that it couldn't find the `aseprite` executable.
We were using
- `Godot 3.3.2 stable`
- `Aseprite v1.2.27-x64`
- `Aseprite Wizard 1.4.0`
We had both configured our PATH, so that Aseprite can be launched from any directory by typing in `aseprite` and double-checked the configure button in the Wizard, which was also set to only `aseprite` (the default).

**Comment by viniciusgerevini** [comment]
Hello @benthillerkus,
Thanks for reporting this. I did a quick search here and I saw mentions of `OS.execute` (the command I use in the plugin) not picking up commands from the path in Windows. I'll try to reproduce this issue here and see if there is any way to fix it. As a workaround, you can set the whole path in the plugin and it should work fine. Not ideal as you probably prefer to use the already configured executable, but at least you will be able to use the plugin in the mean time.
Cheers.

**Comment by benthillerkus** [comment]
Ok, this is so odd, but I tried it again today, and it did work. I didn't change anything, and restarting computers was something we already tried on Sunday.

Either way, thanks for your response 🥇

**Comment by viniciusgerevini** [comment]
Thanks @benthillerkus . It is good to know. :+1:
